import OmegaProper.Decision.Dominance

/-!
OmegaProper.Decision.BlackwellDeterministic

Deterministic finite Blackwell-shaped conservativity wrapper for ODT1.

This file records the deterministic factorization/simulation surface. A coarser
experiment factors through a finer experiment exactly when every policy over
the coarser observation can be simulated by a policy over the finer observation
with the same statewise actions.

It does not implement stochastic Blackwell theory, Le Cam deficiency,
probabilistic garbling, expected utility, ODT2, value, agency, identity,
quantum structure, or Omega validation.
-/

namespace OmegaProper
namespace Decision
namespace BlackwellDeterministic

open Dominance

universe u v w a o

/-- A deterministic experiment is an observation map from states. -/
structure DetExperiment (State : Type u) (Obs : Type v) where
  observe : State -> Obs

/--
`F` factors through `E`: the `F` observation can be recovered from the `E`
observation.

Reading: `E` is at least as informative as `F`.
-/
structure DetFactorization
    {State : Type u} {ObsE : Type v} {ObsF : Type w}
    (E : DetExperiment State ObsE)
    (F : DetExperiment State ObsF) where
  map : ObsE -> ObsF
  commutes : forall s : State, F.observe s = map (E.observe s)

/-- Deterministic Blackwell dominance as factorization. -/
def DetBlackwellDominates
    {State : Type u} {ObsE : Type v} {ObsF : Type w}
    (E : DetExperiment State ObsE)
    (F : DetExperiment State ObsF) : Prop :=
  Nonempty (DetFactorization E F)

/--
`E` simulates `F` policies when every policy over `F` observations can be run
through `E` observations with the same statewise action.

The action type ranges over the observation universe of `F`. This admits the
identity policy on `ObsF`, which is the only universe-sensitive ingredient
needed to recover a deterministic factorization from universal simulation.
-/
def SimulatesPolicies
    {State : Type u} {ObsE : Type v} {ObsF : Type w}
    (E : DetExperiment State ObsE)
    (F : DetExperiment State ObsF) : Prop :=
  forall {Act : Type w} (policyF : ObsF -> Act),
    exists policyE : ObsE -> Act,
      forall s : State, policyE (E.observe s) = policyF (F.observe s)

/-- Compile a policy over the coarser observation into one over the finer one. -/
def compilePolicy
    {State : Type u} {ObsE : Type v} {ObsF : Type w} {Act : Type a}
    {E : DetExperiment State ObsE}
    {F : DetExperiment State ObsF}
    (h : DetFactorization E F)
    (policy : ObsF -> Act) :
    ObsE -> Act :=
  fun eObs => policy (h.map eObs)

/-- The compiled policy takes the same statewise action as the original policy. -/
theorem compilePolicy_statewise
    {State : Type u} {ObsE : Type v} {ObsF : Type w} {Act : Type a}
    {E : DetExperiment State ObsE}
    {F : DetExperiment State ObsF}
    (h : DetFactorization E F)
    (policy : ObsF -> Act)
    (s : State) :
    compilePolicy h policy (E.observe s) = policy (F.observe s) := by
  unfold compilePolicy
  rw [<- h.commutes s]

/-- Factorization gives policy simulation by compiling along the factor map. -/
theorem factorization_implies_policy_simulation
    {State : Type u} {ObsE : Type v} {ObsF : Type w}
    {E : DetExperiment State ObsE}
    {F : DetExperiment State ObsF}
    (h : DetFactorization E F) :
    SimulatesPolicies E F := by
  intro Act policyF
  exact ⟨compilePolicy h policyF, compilePolicy_statewise h policyF⟩

/--
Universal policy simulation recovers the factor map by using `ObsF` itself as
the action type and the identity `F`-policy.
-/
theorem policy_simulation_implies_factorization
    {State : Type u} {ObsE : Type v} {ObsF : Type w}
    {E : DetExperiment State ObsE}
    {F : DetExperiment State ObsF}
    (h : SimulatesPolicies E F) :
    DetBlackwellDominates E F := by
  rcases h (fun obs : ObsF => obs) with ⟨policyE, hStatewise⟩
  exact ⟨
    { map := policyE
      commutes := by
        intro s
        exact (hStatewise s).symm }⟩

/--
Deterministic Blackwell dominance closes as factorization iff universal policy
simulation.
-/
theorem detBlackwellDominates_iff_policy_simulation
    {State : Type u} {ObsE : Type v} {ObsF : Type w}
    {E : DetExperiment State ObsE}
    {F : DetExperiment State ObsF} :
    DetBlackwellDominates E F <-> SimulatesPolicies E F := by
  constructor
  · intro hDom
    rcases hDom with ⟨hFactor⟩
    exact factorization_implies_policy_simulation hFactor
  · exact policy_simulation_implies_factorization

/-- Failure of factorization is exactly failure of universal policy simulation. -/
theorem not_factorization_implies_policy_gap
    {State : Type u} {ObsE : Type v} {ObsF : Type w}
    {E : DetExperiment State ObsE}
    {F : DetExperiment State ObsF}
    (h : Not (DetBlackwellDominates E F)) :
    Not (SimulatesPolicies E F) := by
  intro hSim
  exact h ((detBlackwellDominates_iff_policy_simulation).mpr hSim)

/-- Outcome surface generated by a deterministic experiment and policy. -/
def PolicyOutcomeSurface
    {State : Type u} {Obs : Type v} {Act : Type a} {W : Type o}
    (E : DetExperiment State Obs)
    (policy : Obs -> Act)
    (outcome : State -> Act -> W) :
    W -> Prop :=
  fun w => exists s : State, w = outcome s (policy (E.observe s))

/--
Compiled policies preserve the exact outcome surface, state witness by state
witness.
-/
theorem compiled_policy_surface_iff
    {State : Type u} {ObsE : Type v} {ObsF : Type w}
    {Act : Type a} {W : Type o}
    {E : DetExperiment State ObsE}
    {F : DetExperiment State ObsF}
    (h : DetFactorization E F)
    (policy : ObsF -> Act)
    (outcome : State -> Act -> W)
    (w0 : W) :
    PolicyOutcomeSurface E (compilePolicy h policy) outcome w0 <->
      PolicyOutcomeSurface F policy outcome w0 := by
  unfold PolicyOutcomeSurface compilePolicy
  constructor
  · rintro ⟨s, hs⟩
    exact ⟨s, by simpa [<- h.commutes s] using hs⟩
  · rintro ⟨s, hs⟩
    exact ⟨s, by simpa [<- h.commutes s] using hs⟩

/-- Equivalent predicate surfaces induce Hoare dominance in both directions. -/
private theorem hoare_equiv_of_forall_iff
    {W : Type o} [Preorder W]
    {A B : W -> Prop}
    (h : forall w : W, A w <-> B w) :
    HoareDominates A B /\ HoareDominates B A := by
  constructor
  · intro b hB
    exact ⟨b, (h b).mpr hB, le_rfl⟩
  · intro a hA
    exact ⟨a, (h a).mp hA, le_rfl⟩

/-- Equivalent predicate surfaces induce Smyth dominance in both directions. -/
private theorem smyth_equiv_of_forall_iff
    {W : Type o} [Preorder W]
    {A B : W -> Prop}
    (h : forall w : W, A w <-> B w) :
    SmythDominates A B /\ SmythDominates B A := by
  constructor
  · intro a hA
    exact ⟨a, (h a).mp hA, le_rfl⟩
  · intro b hB
    exact ⟨b, (h b).mpr hB, le_rfl⟩

/--
Every coarser-observation policy compiled through a deterministic
factorization is Hoare-equivalent to the original policy outcome surface.
-/
theorem compiled_policy_hoare_equiv
    {State : Type u} {ObsE : Type v} {ObsF : Type w}
    {Act : Type a} {W : Type o} [Preorder W]
    {E : DetExperiment State ObsE}
    {F : DetExperiment State ObsF}
    (h : DetFactorization E F)
    (policy : ObsF -> Act)
    (outcome : State -> Act -> W) :
    HoareDominates
      (PolicyOutcomeSurface E (compilePolicy h policy) outcome)
      (PolicyOutcomeSurface F policy outcome)
    /\
    HoareDominates
      (PolicyOutcomeSurface F policy outcome)
      (PolicyOutcomeSurface E (compilePolicy h policy) outcome) :=
  hoare_equiv_of_forall_iff (compiled_policy_surface_iff h policy outcome)

/--
Every coarser-observation policy compiled through a deterministic
factorization is Smyth-equivalent to the original policy outcome surface.
-/
theorem compiled_policy_smyth_equiv
    {State : Type u} {ObsE : Type v} {ObsF : Type w}
    {Act : Type a} {W : Type o} [Preorder W]
    {E : DetExperiment State ObsE}
    {F : DetExperiment State ObsF}
    (h : DetFactorization E F)
    (policy : ObsF -> Act)
    (outcome : State -> Act -> W) :
    SmythDominates
      (PolicyOutcomeSurface E (compilePolicy h policy) outcome)
      (PolicyOutcomeSurface F policy outcome)
    /\
    SmythDominates
      (PolicyOutcomeSurface F policy outcome)
      (PolicyOutcomeSurface E (compilePolicy h policy) outcome) :=
  smyth_equiv_of_forall_iff (compiled_policy_surface_iff h policy outcome)

/-- Compiled deterministic policies are Plotkin-equivalent. -/
theorem compiled_policy_plotkin_equiv
    {State : Type u} {ObsE : Type v} {ObsF : Type w}
    {Act : Type a} {W : Type o} [Preorder W]
    {E : DetExperiment State ObsE}
    {F : DetExperiment State ObsF}
    (h : DetFactorization E F)
    (policy : ObsF -> Act)
    (outcome : State -> Act -> W) :
    PlotkinDominates
      (PolicyOutcomeSurface E (compilePolicy h policy) outcome)
      (PolicyOutcomeSurface F policy outcome)
    /\
    PlotkinDominates
      (PolicyOutcomeSurface F policy outcome)
      (PolicyOutcomeSurface E (compilePolicy h policy) outcome) := by
  have hHoare := compiled_policy_hoare_equiv h policy outcome
  have hSmyth := compiled_policy_smyth_equiv h policy outcome
  exact ⟨⟨hHoare.left, hSmyth.left⟩, ⟨hHoare.right, hSmyth.right⟩⟩

/--
Kernel refinement: any two states indistinguishable by `E` are also
indistinguishable by `F`.
-/
def KernelRefines
    {State : Type u} {ObsE : Type v} {ObsF : Type w}
    (E : DetExperiment State ObsE)
    (F : DetExperiment State ObsF) : Prop :=
  forall s t : State, E.observe s = E.observe t -> F.observe s = F.observe t

/-- Deterministic factorization implies kernel refinement. -/
theorem factorization_kernel_refines
    {State : Type u} {ObsE : Type v} {ObsF : Type w}
    {E : DetExperiment State ObsE}
    {F : DetExperiment State ObsF}
    (h : DetFactorization E F) :
    KernelRefines E F := by
  intro s t hEq
  calc
    F.observe s = h.map (E.observe s) := h.commutes s
    _ = h.map (E.observe t) := by rw [hEq]
    _ = F.observe t := (h.commutes t).symm

end BlackwellDeterministic
end Decision
end OmegaProper
