import OmegaCore.DistTrans

/-!
OmegaCore.MarginalJoint

Finite distinction-transport counterexample:
recovering each component/marginal distinction does not force recovery of a
strictly joint distinction.

This module stays at the support-level `DistTransport` layer. It does not define
compatibility, process bundles, proto-valuers, empirical adapters, Future Field
Atlas semantics, value, valuerhood, or Omega validation.
-/

namespace OmegaCore

namespace MarginalJoint

/-- Source distinctions: trivial, two marginal distinctions, and a strictly
joint distinction. -/
inductive SrcD where
  | bot
  | margA
  | margB
  | joint
  deriving DecidableEq

/-- Target distinctions: trivial plus two marginal outputs. There is no target
distinction fine enough to recover the source joint distinction. -/
inductive TgtD where
  | bot
  | outA
  | outB
  deriving DecidableEq

/-- Source refinement preorder:
`bot <= margA <= joint` and `bot <= margB <= joint`, with marginals
incomparable. -/
def SrcLe : SrcD -> SrcD -> Prop
  | SrcD.bot, _ => True
  | SrcD.margA, SrcD.margA => True
  | SrcD.margA, SrcD.joint => True
  | SrcD.margB, SrcD.margB => True
  | SrcD.margB, SrcD.joint => True
  | SrcD.joint, SrcD.joint => True
  | _, _ => False

/-- Target refinement preorder:
`bot <= outA` and `bot <= outB`, with outputs incomparable. -/
def TgtLe : TgtD -> TgtD -> Prop
  | TgtD.bot, _ => True
  | TgtD.outA, TgtD.outA => True
  | TgtD.outB, TgtD.outB => True
  | _, _ => False

theorem srcLe_refl (d : SrcD) : SrcLe d d := by
  cases d <;> simp [SrcLe]

theorem srcLe_trans {a b c : SrcD} :
    SrcLe a b -> SrcLe b c -> SrcLe a c := by
  cases a <;> cases b <;> cases c <;> simp [SrcLe]

theorem tgtLe_refl (d : TgtD) : TgtLe d d := by
  cases d <;> simp [TgtLe]

theorem tgtLe_trans {a b c : TgtD} :
    TgtLe a b -> TgtLe b c -> TgtLe a c := by
  cases a <;> cases b <;> cases c <;> simp [TgtLe]

/-- Source distinction preorder frame. -/
def SrcFrame : PreorderFrame SrcD where
  le := SrcLe
  le_refl := srcLe_refl
  le_trans := @srcLe_trans

/-- Target distinction preorder frame. -/
def TgtFrame : PreorderFrame TgtD where
  le := TgtLe
  le_refl := tgtLe_refl
  le_trans := @tgtLe_trans

/-- Transport relation generated by marginal recovery:
source distinctions weak enough for `margA` may recover into `outA`, and source
distinctions weak enough for `margB` may recover into `outB`. -/
def PhiRel (d : SrcD) (e : TgtD) : Prop :=
  (SrcLe d SrcD.margA /\ TgtLe TgtD.outA e) \/
    (SrcLe d SrcD.margB /\ TgtLe TgtD.outB e)

/-- The marginal transport is closed under source weakening and target
strengthening. -/
def Phi : DistTransport SrcFrame TgtFrame where
  rel := PhiRel
  closed := by
    intro p' p q q' hp h hq
    cases h with
    | inl hA =>
        exact Or.inl
          (And.intro
            (srcLe_trans hp hA.left)
            (tgtLe_trans hA.right hq))
    | inr hB =>
        exact Or.inr
          (And.intro
            (srcLe_trans hp hB.left)
            (tgtLe_trans hB.right hq))

/-- Transport-level non-erasure for a declared source requirement set. -/
def TransportNonErasing
    (Phi : DistTransport SrcFrame TgtFrame)
    (Req : SrcD -> Prop) : Prop :=
  forall d, Req d -> exists e, Phi.rel d e

/-- Requirement set containing the two marginal distinctions. -/
def ReqMarginal : SrcD -> Prop
  | SrcD.margA => True
  | SrcD.margB => True
  | _ => False

/-- Requirement set containing the strictly joint distinction. -/
def ReqJoint : SrcD -> Prop
  | SrcD.joint => True
  | _ => False

/-- The marginal distinctions are non-erased by `Phi`. -/
theorem marginal_non_erasing :
    TransportNonErasing Phi ReqMarginal := by
  intro d hReq
  cases d <;> simp [ReqMarginal] at hReq
  case margA =>
    exact Exists.intro TgtD.outA
      (Or.inl
        (And.intro
          (by simp [SrcLe])
          (by simp [TgtLe])))
  case margB =>
    exact Exists.intro TgtD.outB
      (Or.inr
        (And.intro
          (by simp [SrcLe])
          (by simp [TgtLe])))

/-- The strictly joint distinction is not non-erased by `Phi`. -/
theorem joint_not_non_erasing :
    Not (TransportNonErasing Phi ReqJoint) := by
  intro h
  have hJoint : exists e, Phi.rel SrcD.joint e :=
    h SrcD.joint (by simp [ReqJoint])
  cases hJoint with
  | intro e he =>
      cases e <;> simp [Phi, PhiRel, SrcLe, TgtLe] at he

/-- Marginal-like non-erasure does not imply joint non-erasure. -/
theorem marginal_non_erasure_not_joint_non_erasure :
    TransportNonErasing Phi ReqMarginal /\
      Not (TransportNonErasing Phi ReqJoint) := by
  exact And.intro marginal_non_erasing joint_not_non_erasing

end MarginalJoint

end OmegaCore
