import OmegaProper.Compatibility.JointPresentation
import OmegaProper.BaselineWitnesses
import OmegaProper.Scaffolds.CompletionCounterexamples
import OmegaProper.Scaffolds.FiniteMaximal
import OmegaProper.Trajectory.AlphaConsequenceSeed
import OmegaProper.Trajectory.AlphaConsequenceSeedExamples
import OmegaProper.Trajectory.CarriedDistinction
import OmegaProper.Trajectory.ClassSoundnessAsClique
import OmegaProper.Trajectory.ConsequenceClasses
import OmegaProper.Trajectory.ConsequenceComparison
import OmegaProper.Trajectory.DeformationProfile
import OmegaProper.Trajectory.DeformationProfileExamples
import OmegaProper.Trajectory.DistinctionSupport
import OmegaProper.Trajectory.ConsequenceDiscipline
import OmegaProper.Trajectory.ConsequencePanelDiscipline
import OmegaProper.Trajectory.ConsequenceRelation
import OmegaProper.Trajectory.HiddenLossUnderBadPresentation
import OmegaProper.Trajectory.HiddenJointViabilityLossUnderBadPresentation
import OmegaProper.Trajectory.HiddenViabilityLossUnderBadPresentation
import OmegaProper.Trajectory.IrreversibleReachLoss
import OmegaProper.Trajectory.IrreversibleViabilityLoss
import OmegaProper.Trajectory.JointViability
import OmegaProper.Trajectory.LossAwarePresentationContract
import OmegaProper.Trajectory.LossAwarePresentationConstructors
import OmegaProper.Trajectory.LossAwarePresentationStrictness
import OmegaProper.Trajectory.PathCarriedDistinction
import OmegaProper.Trajectory.PresentationInvariant
import OmegaProper.Trajectory.PresentationInvariantExamples
import OmegaProper.Trajectory.PredicateFixpoint
import OmegaProper.Trajectory.PhantomReachability
import OmegaProper.Trajectory.PhantomViability
import OmegaProper.Trajectory.ProtoTeleologicalSeed
import OmegaProper.Trajectory.ProtoTeleologicalSeedDiscipline
import OmegaProper.Trajectory.ProtoTeleologicalSeedExamples
import OmegaProper.Trajectory.ProtoTeleologicalProfile
import OmegaProper.Trajectory.ProfileAbstraction
import OmegaProper.Trajectory.Quotient
import OmegaProper.Trajectory.ReachabilityReflection
import OmegaProper.Trajectory.ReachabilityViability
import OmegaProper.Trajectory.RecurrentViableClass
import OmegaProper.Trajectory.SafeLossVisibility
import OmegaProper.Trajectory.SafePresentationContract
import OmegaProper.Trajectory.SoundQuotient
import OmegaProper.Trajectory.SoundPresentationFamily
import OmegaProper.Trajectory.SupportMinimality
import OmegaProper.Trajectory.SupportRestriction
import OmegaProper.Trajectory.SustainingSafePrefixes
import OmegaProper.Trajectory.SustainingViableClass
import OmegaProper.Trajectory.TargetPresentationInvariant
import OmegaProper.Trajectory.TrajectorySemantics
import OmegaProper.Trajectory.ViableTrajectoryLanguage
import OmegaProper.Trajectory.ViabilityReflection

/-!
OmegaProper umbrella.

Downstream candidate-theory scaffolds. This layer is intentionally thin and
does not claim that Omega proper is solved.
-/
