import OmegaProper.Compatibility.JointPresentation
import OmegaProper.BaselineWitnesses
import OmegaProper.Scaffolds.CompletionCounterexamples
import OmegaProper.Scaffolds.FiniteMaximal
import OmegaProper.Trajectory.AlphaConsequenceSeed
import OmegaProper.Trajectory.AlphaConsequenceSeedExamples
import OmegaProper.Trajectory.ClassSoundnessAsClique
import OmegaProper.Trajectory.ConsequenceClasses
import OmegaProper.Trajectory.ConsequenceComparison
import OmegaProper.Trajectory.DeformationProfile
import OmegaProper.Trajectory.DeformationProfileExamples
import OmegaProper.Trajectory.ConsequenceDiscipline
import OmegaProper.Trajectory.ConsequencePanelDiscipline
import OmegaProper.Trajectory.ConsequenceRelation
import OmegaProper.Trajectory.PresentationInvariant
import OmegaProper.Trajectory.PresentationInvariantExamples
import OmegaProper.Trajectory.PredicateFixpoint
import OmegaProper.Trajectory.ProtoTeleologicalSeed
import OmegaProper.Trajectory.ProtoTeleologicalSeedDiscipline
import OmegaProper.Trajectory.ProtoTeleologicalSeedExamples
import OmegaProper.Trajectory.ProtoTeleologicalProfile
import OmegaProper.Trajectory.ProfileAbstraction
import OmegaProper.Trajectory.Quotient
import OmegaProper.Trajectory.SoundQuotient
import OmegaProper.Trajectory.SoundPresentationFamily
import OmegaProper.Trajectory.TargetPresentationInvariant

/-!
OmegaProper umbrella.

Downstream candidate-theory scaffolds. This layer is intentionally thin and
does not claim that Omega proper is solved.
-/
