"""Schema-driven finite relational adapter.

The package exposes a small universal finite relational model plus generic
audits over role-selected profiles.
"""

from omega.adapters.finite_relational.audits import AuditResult, run_audit, run_declared_audits
from omega.adapters.finite_relational.adversarial_search import (
    GeneratedAdapterCase,
    generate_adversarial_cases,
)
from omega.adapters.finite_relational.controlled_experiment import (
    ControlledExperimentCase,
    ControlledExperimentFamily,
    controlled_experiment_summary,
    generate_controlled_experiment,
)
from omega.adapters.finite_relational.derived_graph import (
    compile_derived_graph,
    compile_derived_graph_path,
    load_derived_graph_path,
)
from omega.adapters.finite_relational.deterministic_recovery import (
    DeterministicLayerFamily,
    all_binary_targets,
    all_observations,
    deterministic_layer_summary,
    function_recoverable_from_observation,
    generate_deterministic_layer_study,
    minimal_sufficient_observation,
    observation_refines,
    recoverable_targets,
    target_recoverable_from_observation,
)
from omega.adapters.finite_relational.stochastic_recovery import (
    Channel,
    Decoder,
    Observation as StochasticObservation,
    OptimizedDecoderResult,
    StochasticRecoveryFamily,
    SupportAmbiguity,
    TargetFunction,
    all_deterministic_decoders,
    coarsen_observation,
    compose_coarse_decoder_through_fine,
    fraction_to_text,
    generate_stochastic_recovery_study,
    observation_refines_outputs,
    optimized_worst_case_decoder,
    stochastic_recovery_summary,
    success_by_source,
    support_ambiguities,
    support_exact_recoverable,
    validate_channel,
    worst_case_success,
)
from omega.adapters.finite_relational.finite_grid import (
    compile_finite_grid,
    compile_finite_grid_path,
    load_finite_grid_path,
)
from omega.adapters.finite_relational.grid_obstacle_experiment import (
    GridObstacleCase,
    GridObstacleStudy,
    compile_grid_obstacle_source,
    generate_grid_obstacle_study,
)
from omega.adapters.finite_relational.model import (
    FiniteFunction,
    FiniteRelationalModel,
    Predicate,
    Relation,
    SchemaError,
    load_model,
    load_model_path,
    model_digest,
    validate_provenance,
)

__all__ = [
    "AuditResult",
    "Channel",
    "Decoder",
    "FiniteFunction",
    "FiniteRelationalModel",
    "GeneratedAdapterCase",
    "ControlledExperimentCase",
    "ControlledExperimentFamily",
    "DeterministicLayerFamily",
    "GridObstacleCase",
    "OptimizedDecoderResult",
    "GridObstacleStudy",
    "Predicate",
    "Relation",
    "SchemaError",
    "StochasticObservation",
    "StochasticRecoveryFamily",
    "SupportAmbiguity",
    "TargetFunction",
    "all_binary_targets",
    "all_deterministic_decoders",
    "all_observations",
    "coarsen_observation",
    "compile_derived_graph",
    "compile_derived_graph_path",
    "compile_finite_grid",
    "compile_finite_grid_path",
    "compile_grid_obstacle_source",
    "compose_coarse_decoder_through_fine",
    "deterministic_layer_summary",
    "fraction_to_text",
    "function_recoverable_from_observation",
    "generate_adversarial_cases",
    "generate_controlled_experiment",
    "generate_deterministic_layer_study",
    "generate_grid_obstacle_study",
    "generate_stochastic_recovery_study",
    "controlled_experiment_summary",
    "load_model",
    "load_model_path",
    "load_derived_graph_path",
    "load_finite_grid_path",
    "minimal_sufficient_observation",
    "model_digest",
    "observation_refines",
    "observation_refines_outputs",
    "optimized_worst_case_decoder",
    "recoverable_targets",
    "run_audit",
    "run_declared_audits",
    "stochastic_recovery_summary",
    "success_by_source",
    "support_ambiguities",
    "support_exact_recoverable",
    "target_recoverable_from_observation",
    "validate_channel",
    "validate_provenance",
    "worst_case_success",
]
