"""Schema-driven finite relational adapter.

The package exposes a small universal finite relational model plus generic
audits over role-selected profiles.
"""

from omega.adapters.finite_relational.audits import AuditResult, run_audit, run_declared_audits
from omega.adapters.finite_relational.adversarial_search import (
    GeneratedAdapterCase,
    generate_adversarial_cases,
)
from omega.adapters.finite_relational.controlled_experiment import (
    ControlledExperimentCase,
    ControlledExperimentFamily,
    controlled_experiment_summary,
    generate_controlled_experiment,
)
from omega.adapters.finite_relational.derived_graph import (
    compile_derived_graph,
    compile_derived_graph_path,
    load_derived_graph_path,
)
from omega.adapters.finite_relational.deterministic_recovery import (
    DeterministicLayerFamily,
    all_binary_targets,
    all_observations,
    deterministic_layer_summary,
    function_recoverable_from_observation,
    generate_deterministic_layer_study,
    minimal_sufficient_observation,
    observation_refines,
    recoverable_targets,
    target_recoverable_from_observation,
)
from omega.adapters.finite_relational.stochastic_recovery import (
    Channel,
    Decoder,
    Observation as StochasticObservation,
    OptimizedDecoderResult,
    RandomizedDecoder,
    StochasticRecoveryFamily,
    SupportAmbiguity,
    TargetFunction,
    all_deterministic_decoders,
    coarsen_observation,
    compose_coarse_decoder_through_fine,
    fraction_to_text,
    generate_stochastic_recovery_study,
    observation_refines_outputs,
    optimized_worst_case_decoder,
    randomized_success_by_source,
    stochastic_recovery_summary,
    success_by_source,
    support_ambiguities,
    support_exact_recoverable,
    validate_channel,
    worst_case_success,
)
from omega.adapters.finite_relational.stochastic_continuation_loss import (
    StochasticContinuationFamily,
    TransitionKernel,
    distribution_after_horizon,
    generate_stochastic_continuation_loss_study,
    hit_probability_within_horizon,
    hit_profile,
    stochastic_continuation_loss_summary,
    validate_transition_kernel,
)
from omega.adapters.finite_relational.stochastic_policy_dynamics import (
    ActionKernel,
    HypothesisCheck,
    Policy,
    PolicyDynamicsFamily,
    generate_policy_dynamics_study,
    induced_transition_kernel,
    policy_dynamics_summary,
    policy_hit_probability_within_horizon,
    support_summary_for_policy_kernel,
    validate_action_kernel,
)
from omega.adapters.finite_relational.finite_grid import (
    compile_finite_grid,
    compile_finite_grid_path,
    load_finite_grid_path,
)
from omega.adapters.finite_relational.facts import (
    common_target_predicates,
    common_visible_pairs,
    predicate_respects_presentation,
    presentation_fact_closure_facts,
)
from omega.adapters.finite_relational.grid_obstacle_experiment import (
    GridObstacleCase,
    GridObstacleStudy,
    compile_grid_obstacle_source,
    generate_grid_obstacle_study,
)
from omega.adapters.finite_relational.model import (
    FiniteFunction,
    FiniteRelationalModel,
    Predicate,
    Relation,
    SchemaError,
    load_model,
    load_model_path,
    model_digest,
    validate_provenance,
)

__all__ = [
    "AuditResult",
    "ActionKernel",
    "Channel",
    "Decoder",
    "FiniteFunction",
    "FiniteRelationalModel",
    "GeneratedAdapterCase",
    "ControlledExperimentCase",
    "ControlledExperimentFamily",
    "DeterministicLayerFamily",
    "GridObstacleCase",
    "HypothesisCheck",
    "OptimizedDecoderResult",
    "Policy",
    "PolicyDynamicsFamily",
    "RandomizedDecoder",
    "GridObstacleStudy",
    "Predicate",
    "Relation",
    "SchemaError",
    "StochasticObservation",
    "StochasticContinuationFamily",
    "StochasticRecoveryFamily",
    "SupportAmbiguity",
    "TargetFunction",
    "TransitionKernel",
    "all_binary_targets",
    "all_deterministic_decoders",
    "all_observations",
    "coarsen_observation",
    "compile_derived_graph",
    "compile_derived_graph_path",
    "compile_finite_grid",
    "compile_finite_grid_path",
    "compile_grid_obstacle_source",
    "common_target_predicates",
    "common_visible_pairs",
    "compose_coarse_decoder_through_fine",
    "deterministic_layer_summary",
    "distribution_after_horizon",
    "fraction_to_text",
    "function_recoverable_from_observation",
    "generate_adversarial_cases",
    "generate_controlled_experiment",
    "generate_deterministic_layer_study",
    "generate_grid_obstacle_study",
    "generate_policy_dynamics_study",
    "generate_stochastic_continuation_loss_study",
    "generate_stochastic_recovery_study",
    "controlled_experiment_summary",
    "load_model",
    "load_model_path",
    "load_derived_graph_path",
    "load_finite_grid_path",
    "minimal_sufficient_observation",
    "model_digest",
    "observation_refines",
    "observation_refines_outputs",
    "optimized_worst_case_decoder",
    "predicate_respects_presentation",
    "presentation_fact_closure_facts",
    "randomized_success_by_source",
    "recoverable_targets",
    "run_audit",
    "run_declared_audits",
    "stochastic_recovery_summary",
    "stochastic_continuation_loss_summary",
    "success_by_source",
    "support_ambiguities",
    "support_exact_recoverable",
    "target_recoverable_from_observation",
    "validate_channel",
    "validate_transition_kernel",
    "validate_provenance",
    "worst_case_success",
    "hit_probability_within_horizon",
    "hit_profile",
    "induced_transition_kernel",
    "policy_dynamics_summary",
    "policy_hit_probability_within_horizon",
    "support_summary_for_policy_kernel",
    "validate_action_kernel",
]
