import OmegaProper.Decision.License
import OmegaProper.Decision.Examples
import OmegaProper.Decision.RobustCorridor
import OmegaProper.Decision.RobustCorridorExamples
import OmegaProper.Decision.AmbiguityFamily
import OmegaProper.Decision.AmbiguityFamilyExamples
import OmegaProper.Decision.Containment
import OmegaProper.Decision.ContainmentExamples
import OmegaProper.Decision.HistoryContainment
import OmegaProper.Decision.HistoryContainmentExamples
import OmegaProper.Decision.TrajectoryBridge
import OmegaProper.Decision.TrajectoryBridgeExamples
import OmegaProper.Decision.TrajectoryConverse
import OmegaProper.Decision.TrajectoryConverseExamples
import OmegaProper.Decision.AdaptiveFixedWorld
import OmegaProper.Decision.AdaptiveFixedWorldExamples
import OmegaProper.Decision.AdaptiveObservation
import OmegaProper.Decision.RecoveryFrame
import OmegaProper.Decision.RecoveryFrameExamples
import OmegaProper.Decision.RecoveryAwareCorridor
import OmegaProper.Decision.RecoveryAwareCorridorExamples
import OmegaProper.Decision.RecoveryAwareCorridorPhantom
import OmegaProper.Decision.RecoveryLossStress
import OmegaProper.Decision.NonrecoverableLossDominance
import OmegaProper.Decision.NonrecoverableLossDominanceExamples
import OmegaProper.Decision.ExpansionDominance
import OmegaProper.Decision.ExpansionDominanceExamples
import OmegaProper.Decision.TerminationSupremum
import OmegaProper.Decision.CertificateStaleness
import OmegaProper.Decision.AnswerableScope
import OmegaProper.Decision.Dominance
import OmegaProper.Decision.DominanceExamples
import OmegaProper.Decision.DominanceAcceptance
import OmegaProper.Decision.DominanceAcceptanceExamples
import OmegaProper.Decision.DominanceFinite
import OmegaProper.Decision.DominanceFiniteExamples
import OmegaProper.Decision.BlackwellDeterministic
import OmegaProper.Decision.BlackwellDeterministicExamples
import OmegaProper.Decision.BlackwellStochastic
import OmegaProper.Decision.BlackwellStochasticExamples
import OmegaProper.Decision.Arbitration
import OmegaProper.Decision.ArbitrationExamples

/-!
OmegaProper.Decision umbrella.

ODT0-style decision-floor scaffolding. This namespace is intentionally thin:
it consumes certified presentation/reflection and corridor predicates rather
than deriving value, agency, identity, or a complete decision theory.
-/
