import AlphaCore.Nondegenerate

/-!
AlphaCore.PrimitiveApartness

Alpha-native apartness.

This file stays below consequence, continuation, value, agency, and Omega. It
records the primitive distinction relation generated by `Frame.Sep`.
-/

namespace AlphaCore
namespace Frame

universe u v

/-- Two relata are primitively apart when some primitive distinction separates them. -/
def PrimitiveApart
    (A : Frame.{u, v})
    (x y : A.X) : Prop :=
  exists d : A.Dist, A.Sep d x y

/-- Primitive inseparability is absence of primitive apartness. -/
def PrimitiveInseparable
    (A : Frame.{u, v})
    (x y : A.X) : Prop :=
  Not (PrimitiveApart A x y)

/-- A frame has primitive apartness when some pair is separated by a distinction. -/
def HasPrimitiveApartness
    (A : Frame.{u, v}) : Prop :=
  exists x y : A.X, PrimitiveApart A x y

theorem sep_implies_primitiveApart
    {A : Frame.{u, v}}
    {d : A.Dist}
    {x y : A.X}
    (h : A.Sep d x y) :
    PrimitiveApart A x y := by
  exact Exists.intro d h

theorem primitiveApart_symm
    {A : Frame.{u, v}}
    {x y : A.X}
    (h : PrimitiveApart A x y) :
    PrimitiveApart A y x := by
  match h with
  | Exists.intro d hSep =>
      exact Exists.intro d (A.sep_symm d x y hSep)

theorem primitiveApart_irrefl
    {A : Frame.{u, v}}
    {x : A.X} :
    Not (PrimitiveApart A x x) := by
  intro h
  match h with
  | Exists.intro d hSep =>
      exact A.sep_irrefl d x hSep

theorem primitiveApart_implies_not_same
    {A : Frame.{u, v}}
    {x y : A.X}
    (h : PrimitiveApart A x y) :
    Not (x = y) := by
  intro hxy
  subst hxy
  exact primitiveApart_irrefl h

theorem asymmetry_implies_primitiveApart
    {A : Frame.{u, v}}
    {d : A.Dist}
    {x y : A.X}
    (h : A.Asym d x y) :
    PrimitiveApart A x y := by
  exact sep_implies_primitiveApart (A.asym_sep h)

theorem jointWitness_implies_primitiveApart
    {A : Frame.{u, v}}
    (w : JointPrimitiveWitness A) :
    PrimitiveApart A w.x w.y := by
  exact sep_implies_primitiveApart w.sep

theorem asymmetryWitness_implies_primitiveApart
    {A : Frame.{u, v}}
    (w : AsymmetryPrimitiveWitness A) :
    PrimitiveApart A w.x w.y := by
  exact asymmetry_implies_primitiveApart w.asym

theorem primitiveWitness_implies_hasPrimitiveApartness
    {A : Frame.{u, v}}
    (h : PrimitiveWitness A) :
    HasPrimitiveApartness A := by
  match h with
  | Nonempty.intro w =>
      exact Exists.intro w.x
        (Exists.intro w.y
          (asymmetryWitness_implies_primitiveApart w))

theorem identificationCollapse_iff_noPrimitiveApartness
    (A : Frame.{u, v}) :
    IdentificationCollapse A <->
      forall x y : A.X, PrimitiveInseparable A x y := by
  constructor
  case mp =>
    intro hCollapse x y hApart
    match hApart with
    | Exists.intro d hSep =>
        exact hCollapse d x y hSep
  case mpr =>
    intro hNoApart d x y hSep
    exact hNoApart x y (Exists.intro d hSep)

end Frame
end AlphaCore
