import AlphaCore.PrimitiveApartness
import AlphaCore.Reachability

/-!
AlphaCore.PrimitivePath

Relation-generated primitive path structure.

This file treats `Frame.Rel` as the free Alpha-native path generator. It does
not claim that adapter-level process semantics are derived from Alpha.
-/

namespace AlphaCore
namespace Frame

universe u v

/-- Primitive paths are relation-generated reachability paths. -/
abbrev PrimitivePath
    (A : Frame.{u, v})
    (x y : A.X) : Prop :=
  Reach A x y

/-- Mutual primitive reachability is the Alpha-native recurrent-pair floor. -/
def PrimitiveMutualReach
    (A : Frame.{u, v})
    (x y : A.X) : Prop :=
  PrimitivePath A x y /\ PrimitivePath A y x

/--
The primitive mutual-reach carrier generated by endpoints `x` and `y`.

This is a candidate carrier generated from relation paths, not an object
sameness claim.
-/
def PrimitiveMutualReachCarrier
    (A : Frame.{u, v})
    (x y z : A.X) : Prop :=
  PrimitivePath A x z /\
    PrimitivePath A z x /\
    PrimitivePath A y z /\
    PrimitivePath A z y

theorem primitivePath_refl
    (A : Frame.{u, v})
    (x : A.X) :
    PrimitivePath A x x := by
  exact Reach.refl x

theorem primitivePath_of_rel
    {A : Frame.{u, v}}
    {x y : A.X}
    (h : A.Rel x y) :
    PrimitivePath A x y := by
  exact reach_of_rel A h

theorem primitivePath_trans
    {A : Frame.{u, v}}
    {x y z : A.X}
    (hxy : PrimitivePath A x y)
    (hyz : PrimitivePath A y z) :
    PrimitivePath A x z := by
  exact reach_trans A hxy hyz

theorem asymmetry_implies_primitivePath
    {A : Frame.{u, v}}
    {d : A.Dist}
    {x y : A.X}
    (h : A.Asym d x y) :
    PrimitivePath A x y := by
  exact primitivePath_of_rel (A.asym_rel h)

theorem jointWitness_implies_primitivePath
    {A : Frame.{u, v}}
    (w : JointPrimitiveWitness A) :
    PrimitivePath A w.x w.y := by
  exact primitivePath_of_rel w.rel

theorem asymmetryWitness_generates_path_and_apart
    {A : Frame.{u, v}}
    (w : AsymmetryPrimitiveWitness A) :
    PrimitivePath A w.x w.y /\
      PrimitiveApart A w.x w.y := by
  exact And.intro
    (asymmetry_implies_primitivePath w.asym)
    (asymmetryWitness_implies_primitiveApart w)

theorem primitiveMutualReachCarrier_contains_left
    {A : Frame.{u, v}}
    {x y : A.X}
    (h : PrimitiveMutualReach A x y) :
    PrimitiveMutualReachCarrier A x y x := by
  exact And.intro
    (Reach.refl x)
    (And.intro
      (Reach.refl x)
      (And.intro h.right h.left))

theorem primitiveMutualReachCarrier_contains_right
    {A : Frame.{u, v}}
    {x y : A.X}
    (h : PrimitiveMutualReach A x y) :
    PrimitiveMutualReachCarrier A x y y := by
  exact And.intro
    h.left
    (And.intro
      h.right
      (And.intro (Reach.refl y) (Reach.refl y)))

end Frame
end AlphaCore
