import AlphaCore.Primitive

/-!
Alpha reachability.

Reachability is generated by relation. It is graph structure only.
-/

namespace AlphaCore

inductive Reach (A : Frame) : A.X -> A.X -> Prop
  | refl (x : A.X) : Reach A x x
  | step {x y z : A.X} :
      A.Rel x y -> Reach A y z -> Reach A x z

def LocalNonreciprocal (A : Frame) (x y : A.X) : Prop :=
  A.Rel x y /\ Not (A.Rel y x)

def ReachIrreversible (A : Frame) (x y : A.X) : Prop :=
  Reach A x y /\ Not (Reach A y x)

def AsymOneWay (A : Frame) (d : A.Dist) (x y : A.X) : Prop :=
  A.Asym d x y /\ Not (A.Asym d y x)

theorem reach_of_rel
    (A : Frame) {x y : A.X}
    (h : A.Rel x y) : Reach A x y := by
  exact Reach.step h (Reach.refl y)

theorem reach_trans
    (A : Frame) {x y z : A.X}
    (hxy : Reach A x y)
    (hyz : Reach A y z) :
    Reach A x z := by
  induction hxy with
  | refl x =>
      exact hyz
  | step hRel hReach ih =>
      exact Reach.step hRel (ih hyz)

theorem reach_from_sink_eq
    (A : Frame) {x y : A.X}
    (hsink : forall z : A.X, Not (A.Rel x z))
    (h : Reach A x y) : x = y := by
  cases h with
  | refl x =>
      rfl
  | step hRel _ =>
      exact False.elim (hsink _ hRel)

theorem reach_irreversible_not_symmetric
    (A : Frame) {x y : A.X}
    (h : ReachIrreversible A x y) :
    Not (Reach A y x) := by
  exact h.right

end AlphaCore
