"""Build the v3.2 reading edition from its numbered Markdown chapters."""

from __future__ import annotations

import argparse
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
EDITION = ROOT / "docs" / "cosmology" / "v3.2"
OUTPUT = EDITION / "OMEGA_COSMOLOGY_V3_2_COMPLETE.md"


def build() -> str:
    chapters = sorted(EDITION.glob("[0-9][0-9]_*.md"))
    if [p.name[:2] for p in chapters] != [f"{i:02d}" for i in range(17)]:
        raise ValueError("Expected exactly one chapter each, 00 through 16.")
    texts = [p.read_text(encoding="utf-8").strip() for p in chapters]
    titles = [s.splitlines()[0].removeprefix("# ") for s in texts]
    for i, title in enumerate(titles):
        if not title.startswith(f"{i:02d} — "):
            raise ValueError(f"Incorrect chapter heading: {chapters[i]}")
    contents = "\n".join(
        f"- [{title}]({p.name})" for p, title in zip(chapters, titles, strict=True)
    )
    return (
        "# Omega Cosmology v3.2\n\n"
        "**Recursive physical access, composition, recovery and possible value**\n\n"
        "Development edition · 3 October 2026\n\n"
        "Generated from the numbered chapters. Edit those chapters and run "
        "python scripts/build_cosmology_v3_2.py; do not edit this file separately.\n\n"
        "This edition specifies a candidate architecture and its evidence. "
        "The lushness extent and its general decision-theoretic bridge remain open.\n\n"
        "## Contents\n\n" + contents + "\n\n---\n\n" + "\n\n".join(texts) + "\n"
    )


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true", help="Check without rewriting.")
    args = parser.parse_args()
    content = build()
    if args.check:
        if not OUTPUT.exists() or OUTPUT.read_text(encoding="utf-8") != content:
            raise SystemExit("Combined edition is missing or stale.")
        print("v3.2 combined edition matches all 17 source chapters.")
    else:
        OUTPUT.write_text(content, encoding="utf-8", newline="\n")
        print(f"Built {OUTPUT.relative_to(ROOT)} ({len(content.split()):,} words).")


if __name__ == "__main__":
    main()
