import ProtoOmega.Transport.Native

/-!
ProtoOmega.Separations.MarginalJointNative

Alpha-native finite transport counterexample:
recovering each marginal distinction does not force recovery of a strictly
joint distinction.
-/

namespace ProtoOmega
namespace Separations
namespace MarginalJointNative

/-- A one-point carrier for finite Alpha frames used in this separation. -/
inductive Carrier
  | unit
  deriving DecidableEq

/-- Source distinctions: trivial, two marginal distinctions, and a strictly
joint distinction. -/
inductive SrcD
  | bot
  | margA
  | margB
  | joint
  deriving DecidableEq

/-- Target distinctions: trivial plus two marginal outputs. There is no target
distinction fine enough to recover the source joint distinction. -/
inductive TgtD
  | bot
  | outA
  | outB
  deriving DecidableEq

/-- Empty separation over source distinctions. The transport separation uses
presentation-level distinction order, not carrier separation. -/
def SrcSep (_ : SrcD) (_ _ : Carrier) : Prop :=
  False

/-- Empty separation over target distinctions. -/
def TgtSep (_ : TgtD) (_ _ : Carrier) : Prop :=
  False

def srcFrame : AlphaCore.Frame.{0, 0} where
  X := Carrier
  Rel := fun _ _ => False
  Dist := SrcD
  Sep := SrcSep
  sep_irrefl := by
    intro _ _ h
    cases h
  sep_symm := by
    intro _ _ _ h
    cases h
  Asym := fun _ _ _ => False
  asym_rel := by
    intro _ _ _ h
    cases h
  asym_sep := by
    intro _ _ _ h
    cases h

def tgtFrame : AlphaCore.Frame.{0, 0} where
  X := Carrier
  Rel := fun _ _ => False
  Dist := TgtD
  Sep := TgtSep
  sep_irrefl := by
    intro _ _ h
    cases h
  sep_symm := by
    intro _ _ _ h
    cases h
  Asym := fun _ _ _ => False
  asym_rel := by
    intro _ _ _ h
    cases h
  asym_sep := by
    intro _ _ _ h
    cases h

/-- Source refinement preorder:
`bot <= margA <= joint` and `bot <= margB <= joint`, with marginals
incomparable. -/
def SrcLe : SrcD -> SrcD -> Prop
  | SrcD.bot, _ => True
  | SrcD.margA, SrcD.margA => True
  | SrcD.margA, SrcD.joint => True
  | SrcD.margB, SrcD.margB => True
  | SrcD.margB, SrcD.joint => True
  | SrcD.joint, SrcD.joint => True
  | _, _ => False

/-- Target refinement preorder:
`bot <= outA` and `bot <= outB`, with outputs incomparable. -/
def TgtLe : TgtD -> TgtD -> Prop
  | TgtD.bot, _ => True
  | TgtD.outA, TgtD.outA => True
  | TgtD.outB, TgtD.outB => True
  | _, _ => False

theorem srcLe_refl (d : SrcD) : SrcLe d d := by
  cases d <;> simp [SrcLe]

theorem srcLe_trans {a b c : SrcD} :
    SrcLe a b -> SrcLe b c -> SrcLe a c := by
  cases a <;> cases b <;> cases c <;> simp [SrcLe]

theorem tgtLe_refl (d : TgtD) : TgtLe d d := by
  cases d <;> simp [TgtLe]

theorem tgtLe_trans {a b c : TgtD} :
    TgtLe a b -> TgtLe b c -> TgtLe a c := by
  cases a <;> cases b <;> cases c <;> simp [TgtLe]

def srcOrder : Transport.DistOrder srcFrame where
  le := SrcLe
  le_refl := srcLe_refl
  le_trans := @srcLe_trans

def tgtOrder : Transport.DistOrder tgtFrame where
  le := TgtLe
  le_refl := tgtLe_refl
  le_trans := @tgtLe_trans

/-- Transport relation generated by marginal recovery:
source distinctions weak enough for `margA` may recover into `outA`, and source
distinctions weak enough for `margB` may recover into `outB`. -/
def PhiRel (d : SrcD) (e : TgtD) : Prop :=
  (SrcLe d SrcD.margA /\ TgtLe TgtD.outA e) \/
    (SrcLe d SrcD.margB /\ TgtLe TgtD.outB e)

/-- The marginal transport is closed under source weakening and target
strengthening. -/
def Phi : Transport.NativeTransport srcOrder tgtOrder where
  rel := PhiRel
  closed := by
    intro source' source target target' hsrc h htarget
    cases h with
    | inl hA =>
        exact Or.inl
          (And.intro
            (srcLe_trans hsrc hA.left)
            (tgtLe_trans hA.right htarget))
    | inr hB =>
        exact Or.inr
          (And.intro
            (srcLe_trans hsrc hB.left)
            (tgtLe_trans hB.right htarget))

/-- Transport-level non-erasure for a declared source requirement set. -/
def TransportNonErasing
    (Phi : Transport.NativeTransport srcOrder tgtOrder)
    (Req : SrcD -> Prop) : Prop :=
  forall d, Req d -> exists e, Phi.rel d e

/-- Requirement set containing the two marginal distinctions. -/
def ReqMarginal : SrcD -> Prop
  | SrcD.margA => True
  | SrcD.margB => True
  | _ => False

/-- Requirement set containing the strictly joint distinction. -/
def ReqJoint : SrcD -> Prop
  | SrcD.joint => True
  | _ => False

/-- The marginal distinctions are non-erased by `Phi`. -/
theorem marginal_non_erasing :
    TransportNonErasing Phi ReqMarginal := by
  intro d hReq
  cases d <;> simp [ReqMarginal] at hReq
  case margA =>
    exact Exists.intro TgtD.outA
      (Or.inl
        (And.intro
          (by simp [SrcLe])
          (by simp [TgtLe])))
  case margB =>
    exact Exists.intro TgtD.outB
      (Or.inr
        (And.intro
          (by simp [SrcLe])
          (by simp [TgtLe])))

/-- The strictly joint distinction is not non-erased by `Phi`. -/
theorem joint_not_non_erasing :
    Not (TransportNonErasing Phi ReqJoint) := by
  intro h
  have hJoint : exists e, Phi.rel SrcD.joint e :=
    h SrcD.joint (by simp [ReqJoint])
  cases hJoint with
  | intro e he =>
      cases e <;> simp [Phi, PhiRel, SrcLe, TgtLe] at he

/-- Marginal-like non-erasure does not imply joint non-erasure. -/
theorem marginal_non_erasure_not_joint_non_erasure :
    TransportNonErasing Phi ReqMarginal /\
      Not (TransportNonErasing Phi ReqJoint) := by
  exact And.intro marginal_non_erasing joint_not_non_erasing

end MarginalJointNative
end Separations
end ProtoOmega
